/* tslint:disable */
/* eslint-disable */
/*
Synchronize API

Synchronize API allows you to lipsync a video to any audio in any language.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/


export * from './api/animate-api';
export * from './api/lipsync-api';
export * from './api/speak-api';
export * from './api/translate-api';
export * from './api/video-api';
export * from './api/voices-api';

