/*
Synchronize API

Synchronize API allows you to lipsync a video to any audio in any language.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  AnimateApi,
  LipsyncApi,
  SpeakApi,
  TranslateApi,
  VideoApi,
  VoicesApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { SyncLabsCustom } from "./client-custom";

export class SyncLabs extends SyncLabsCustom {
  readonly animate: AnimateApi;
  readonly lipsync: LipsyncApi;
  readonly speak: SpeakApi;
  readonly translate: TranslateApi;
  readonly video: VideoApi;
  readonly voices: VoicesApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.animate = new AnimateApi(configuration);
    this.lipsync = new LipsyncApi(configuration);
    this.speak = new SpeakApi(configuration);
    this.translate = new TranslateApi(configuration);
    this.video = new VideoApi(configuration);
    this.voices = new VoicesApi(configuration);
  }

}
