/* tslint:disable */
/* eslint-disable */
/*
Synchronize API

Synchronize API allows you to lipsync a video to any audio in any language.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { SpeakDto } from '../models';
// @ts-ignore
import { SpeakExtended } from '../models';
// @ts-ignore
import { SpeakInitial } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * SpeakApi - axios parameter creator
 * @export
 */
export const SpeakApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Use the video ID from the POST request to check video status. Keep checking until status is \'completed\' and a download URL is provided.
         * @summary 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSpeech: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getSpeech', 'id', id)
            const localVarPath = `/speak/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id !== undefined ? id : `-id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKey required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "x-api-key", keyParamName: "apiKey", configuration })

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/speak/{id}',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 
         * @param {SpeakDto} speakDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        speak: async (speakDto: SpeakDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'speakDto' is not null or undefined
            assertParamExists('speak', 'speakDto', speakDto)
            const localVarPath = `/speak`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKey required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "x-api-key", keyParamName: "apiKey", configuration })

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: speakDto,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/speak',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(speakDto, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [transcript] A string of text to be spoken by the AI
         * @param {string} [transcriptUrl] A url pointing to a file of text to be spoken by the AI
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        speakCost: async (transcript?: string, transcriptUrl?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/speak/cost`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKey required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "x-api-key", keyParamName: "apiKey", configuration })
            if (transcript !== undefined) {
                localVarQueryParameter['transcript'] = transcript;
            }

            if (transcriptUrl !== undefined) {
                localVarQueryParameter['transcriptUrl'] = transcriptUrl;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/speak/cost',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SpeakApi - functional programming interface
 * @export
 */
export const SpeakApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SpeakApiAxiosParamCreator(configuration)
    return {
        /**
         * Use the video ID from the POST request to check video status. Keep checking until status is \'completed\' and a download URL is provided.
         * @summary 
         * @param {SpeakApiGetSpeechRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSpeech(requestParameters: SpeakApiGetSpeechRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SpeakExtended>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSpeech(requestParameters.id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary 
         * @param {SpeakApiSpeakRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async speak(requestParameters: SpeakApiSpeakRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SpeakInitial>> {
            const speakDto: SpeakDto = {
                transcript: requestParameters.transcript,
                voiceId: requestParameters.voiceId,
                maxCredits: requestParameters.maxCredits,
                webhookUrl: requestParameters.webhookUrl
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.speak(speakDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {SpeakApiSpeakCostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async speakCost(requestParameters: SpeakApiSpeakCostRequest = {}, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.speakCost(requestParameters.transcript, requestParameters.transcriptUrl, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * SpeakApi - factory interface
 * @export
 */
export const SpeakApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SpeakApiFp(configuration)
    return {
        /**
         * Use the video ID from the POST request to check video status. Keep checking until status is \'completed\' and a download URL is provided.
         * @summary 
         * @param {SpeakApiGetSpeechRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSpeech(requestParameters: SpeakApiGetSpeechRequest, options?: AxiosRequestConfig): AxiosPromise<SpeakExtended> {
            return localVarFp.getSpeech(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 
         * @param {SpeakApiSpeakRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        speak(requestParameters: SpeakApiSpeakRequest, options?: AxiosRequestConfig): AxiosPromise<SpeakInitial> {
            return localVarFp.speak(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SpeakApiSpeakCostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        speakCost(requestParameters: SpeakApiSpeakCostRequest = {}, options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.speakCost(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getSpeech operation in SpeakApi.
 * @export
 * @interface SpeakApiGetSpeechRequest
 */
export type SpeakApiGetSpeechRequest = {
    
    /**
    * 
    * @type {string}
    * @memberof SpeakApiGetSpeech
    */
    readonly id: string
    
}

/**
 * Request parameters for speak operation in SpeakApi.
 * @export
 * @interface SpeakApiSpeakRequest
 */
export type SpeakApiSpeakRequest = {
    
} & SpeakDto

/**
 * Request parameters for speakCost operation in SpeakApi.
 * @export
 * @interface SpeakApiSpeakCostRequest
 */
export type SpeakApiSpeakCostRequest = {
    
    /**
    * A string of text to be spoken by the AI
    * @type {string}
    * @memberof SpeakApiSpeakCost
    */
    readonly transcript?: string
    
    /**
    * A url pointing to a file of text to be spoken by the AI
    * @type {string}
    * @memberof SpeakApiSpeakCost
    */
    readonly transcriptUrl?: string
    
}

/**
 * SpeakApiGenerated - object-oriented interface
 * @export
 * @class SpeakApiGenerated
 * @extends {BaseAPI}
 */
export class SpeakApiGenerated extends BaseAPI {
    /**
     * Use the video ID from the POST request to check video status. Keep checking until status is \'completed\' and a download URL is provided.
     * @summary 
     * @param {SpeakApiGetSpeechRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SpeakApiGenerated
     */
    public getSpeech(requestParameters: SpeakApiGetSpeechRequest, options?: AxiosRequestConfig) {
        return SpeakApiFp(this.configuration).getSpeech(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 
     * @param {SpeakApiSpeakRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SpeakApiGenerated
     */
    public speak(requestParameters: SpeakApiSpeakRequest, options?: AxiosRequestConfig) {
        return SpeakApiFp(this.configuration).speak(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SpeakApiSpeakCostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SpeakApiGenerated
     */
    public speakCost(requestParameters: SpeakApiSpeakCostRequest = {}, options?: AxiosRequestConfig) {
        return SpeakApiFp(this.configuration).speakCost(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
