/*
Synchronize API

Synchronize API allows you to lipsync a video to any audio in any language.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AnimateDto
 */
export interface AnimateDto {
    /**
     * A url to the video file to be synchronized -- must be publicly accessible
     * @type {string}
     * @memberof AnimateDto
     */
    'videoUrl': string;
    /**
     * A string of text to be spoken by the AI
     * @type {string}
     * @memberof AnimateDto
     */
    'transcript': string;
    /**
     * The voice to use for audio generation
     * @type {string}
     * @memberof AnimateDto
     */
    'voiceId': string;
    /**
     * The model to use for video generation
     * @type {string}
     * @memberof AnimateDto
     */
    'model'?: string;
    /**
     * Maximum number of credits to use for audio generation. If job exceeds this value, the job will be aborted
     * @type {number}
     * @memberof AnimateDto
     */
    'maxCredits'?: number;
    /**
     * A url to send a notification to upon completion of audio generation
     * @type {string}
     * @memberof AnimateDto
     */
    'webhookUrl'?: string;
}

