/*
Synchronize API

Synchronize API allows you to lipsync a video to any audio in any language.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TranslationJobExtended
 */
export interface TranslationJobExtended {
    /**
     * A unique identifier for the translation job.
     * @type {string}
     * @memberof TranslationJobExtended
     */
    'id': string;
    /**
     * A URL which can be used to download the video.
     * @type {string}
     * @memberof TranslationJobExtended
     */
    'video_url'?: string;
    /**
     * A URL which can be used to download the audio.
     * @type {string}
     * @memberof TranslationJobExtended
     */
    'audio_url': string;
    /**
     * A URL to access the transcript of the video.
     * @type {string}
     * @memberof TranslationJobExtended
     */
    'transcript_url'?: string;
    /**
     * The original URL of the video that was submitted.
     * @type {string}
     * @memberof TranslationJobExtended
     */
    'original_video_url': string;
    /**
     * The source language of the video.
     * @type {string}
     * @memberof TranslationJobExtended
     */
    'source_language': string;
    /**
     * The language into which the video is being translated.
     * @type {string}
     * @memberof TranslationJobExtended
     */
    'target_language'?: string;
    /**
     * The status of the translation job.
     * @type {string}
     * @memberof TranslationJobExtended
     */
    'status': string;
    /**
     * The step of the translation job.
     * @type {string}
     * @memberof TranslationJobExtended
     */
    'step': string;
}

