/*
Synchronize API

Synchronize API allows you to lipsync a video to any audio in any language.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TranslateDto
 */
export interface TranslateDto {
    /**
     * A url to the video file to be translated and synchronized -- must be publicly accessible
     * @type {string}
     * @memberof TranslateDto
     */
    'videoUrl': string;
    /**
     * Target language to translate the video to
     * @type {string}
     * @memberof TranslateDto
     */
    'targetLanguage': string;
    /**
     * Maximum number of credits to use for video generation. If job exceeds this value, the job will be aborted
     * @type {number}
     * @memberof TranslateDto
     */
    'maxCredits'?: number;
    /**
     * A url to send a notification to upon completion of video generation
     * @type {string}
     * @memberof TranslateDto
     */
    'webhookUrl'?: string;
    /**
     * The model to use for video generation.
     * @type {string}
     * @memberof TranslateDto
     */
    'model'?: string;
}

