/*
Synchronize API

Synchronize API allows you to lipsync a video to any audio in any language.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface VideoExtended
 */
export interface VideoExtended {
    /**
     * A unique identifier for the video.
     * @type {string}
     * @memberof VideoExtended
     */
    'id': string;
    /**
     * A URL which can be used to download the video.
     * @type {string}
     * @memberof VideoExtended
     */
    'url'?: string;
    /**
     * The original URL of the video that was submitted.
     * @type {string}
     * @memberof VideoExtended
     */
    'original_video_url': string;
    /**
     * The original URL of the audio that was submitted.
     * @type {string}
     * @memberof VideoExtended
     */
    'original_audio_url': string;
    /**
     * The status of the video.
     * @type {string}
     * @memberof VideoExtended
     */
    'status': string;
    /**
     * A flag to enable / disable post-processing
     * @type {boolean}
     * @memberof VideoExtended
     */
    'synergize': boolean;
    /**
     * The number of credits deducted for the video.
     * @type {number}
     * @memberof VideoExtended
     */
    'credits_deducted': number;
}

